"""Write the host composition (index.html) from one slot table. Both formats share every beat file;
   only the host size changes. A project may have one root composition, so the format is switched here:
     python3 tools/hosts.py            -> vertical 1080x1920 (primary, the committed state)
     python3 tools/hosts.py landscape  -> 1920x1080 (render it, then switch back)"""
import pathlib, re, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
FPS = 60
# (id, start frame, end frame). Overlaps are deliberate: the incoming beat wipes over the outgoing one.
SLOTS = [
    ("principles", 0, 240),
    ("stack", 240, 480),
    ("wordmark", 480, 600),
    ("cross", 600, 720),
    ("palette", 720, 960),
    ("type", 960, 1080),
    ("interface", 1080, 1200),
    ("mark", 1200, 1320),
    ("signoff", 1320, 1470),
]
TOTAL = 1470

def host(w, h):
    s = lambda f: f"{f / FPS:.6g}"
    slots = "\n".join(
        f'      <div id="{cid}" data-composition-id="{cid}" data-composition-src="compositions/{cid}.html" '
        f'data-start="{s(a)}" data-duration="{s(b - a)}" data-track-index="{i % 2}" data-width="{w}" data-height="{h}"></div>'
        for i, (cid, a, b) in enumerate(SLOTS))
    return f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={w}, height={h}" />
    <!-- generated by tools/hosts.py — edit the slot table there, not here -->
    <script src="assets/vendor/gsap.min.js"></script>
    <script src="assets/kit.js"></script>
    <link rel="stylesheet" href="assets/shared.css" />
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{ width: {w}px; height: {h}px; overflow: hidden; background: var(--paper); }}
      #main {{ position: relative; width: {w}px; height: {h}px; overflow: hidden; background: var(--paper); }}
    </style>
  </head>
  <body>
    <div id="main" data-composition-id="main" data-start="0" data-duration="{s(TOTAL)}" data-fps="{FPS}" data-width="{w}" data-height="{h}">
{slots}
      <audio id="launch-mix" src="assets/audio/launch_mix.wav" data-start="0" data-duration="{s(TOTAL)}" data-track-index="4" data-volume="1"></audio>
    </div>
    <script>
      window.__timelines = window.__timelines || {{}};
      const tl = gsap.timeline({{ paused: true }});
      tl.set({{}}, {{}}, {s(TOTAL)});
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
'''

fmt = sys.argv[1] if len(sys.argv) > 1 else "vertical"
w, h = {"vertical": (1080, 1920), "landscape": (1920, 1080)}[fmt]
(ROOT / "index.html").write_text(host(w, h))
# Each beat file declares its own root size too; keep it in step with the host.
for cid, _, _ in SLOTS:
    f = ROOT / "compositions" / f"{cid}.html"
    src = f.read_text()
    out = re.sub(r'(data-composition-id="%s" data-width=")\d+(" data-height=")\d+(")' % re.escape(cid), rf"\g<1>{w}\g<2>{h}\g<3>", src)
    assert out != src or f'data-width="{w}" data-height="{h}"' in src, f"root size attrs not found in {f.name}"
    f.write_text(out)
print(f"index.html -> {fmt} {w}x{h}")
